import { useState } from "react"
import type { BookPublic } from "@/client"

/**
 * Interface for Google Books API response
 */
interface GoogleBookItem {
  id: string
  volumeInfo: {
    title: string
    authors?: string[]
    publisher?: string
    publishedDate?: string
    description?: string
    pageCount?: number
    categories?: string[]
    imageLinks?: {
      thumbnail?: string
      smallThumbnail?: string
    }
    industryIdentifiers?: Array<{
      type: string
      identifier: string
    }>
    averageRating?: number
    ratingsCount?: number
  }
}

/**
 * Transform Google Books API response to our BookPublic format
 */
const transformGoogleBook = (item: GoogleBookItem): Partial<BookPublic> => {
  const isbn =
    item.volumeInfo.industryIdentifiers?.find(
      (id) => id.type === "ISBN_13" || id.type === "ISBN_10"
    )?.identifier || null

  return {
    id: "", // Will be generated by backend
    title: item.volumeInfo.title,
    author: item.volumeInfo.authors?.join(", ") || null,
    isbn,
    publisher: item.volumeInfo.publisher || null,
    published_date: item.volumeInfo.publishedDate || null,
    description: item.volumeInfo.description || null,
    page_count: item.volumeInfo.pageCount || null,
    categories: item.volumeInfo.categories
      ? JSON.stringify(item.volumeInfo.categories)
      : null,
    thumbnail_url: item.volumeInfo.imageLinks?.thumbnail || null,
    google_books_id: item.id,
    average_rating: item.volumeInfo.averageRating || null,
    ratings_count: item.volumeInfo.ratingsCount || null,
  }
}

/**
 * Custom hook for searching Google Books API
 * Note: This uses the public Google Books API directly from the client
 */
const useGoogleBooks = () => {
  const [isSearching, setIsSearching] = useState(false)
  const [searchResults, setSearchResults] = useState<Partial<BookPublic>[]>([])
  const [error, setError] = useState<string | null>(null)

  const searchBooks = async (query: string, maxResults = 10) => {
    if (!query.trim()) {
      setSearchResults([])
      return
    }

    setIsSearching(true)
    setError(null)

    try {
      const response = await fetch(
        `https://www.googleapis.com/books/v1/volumes?q=${encodeURIComponent(
          query
        )}&maxResults=${maxResults}`
      )

      if (!response.ok) {
        throw new Error("Failed to search books")
      }

      const data = await response.json()
      const books = (data.items || []).map(transformGoogleBook)
      setSearchResults(books)
    } catch (err) {
      setError(err instanceof Error ? err.message : "Search failed")
      setSearchResults([])
    } finally {
      setIsSearching(false)
    }
  }

  const clearResults = () => {
    setSearchResults([])
    setError(null)
  }

  return {
    searchBooks,
    isSearching,
    searchResults,
    error,
    clearResults,
  }
}

export default useGoogleBooks
